package disk

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/afero"
	"github.com/supanadit/phpv/domain"
	"github.com/supanadit/phpv/internal/utils"
)

type VersionWrapperManager struct {
	fs          afero.Fs
	silo        *domain.Silo
	phpVersion  string
	wrapperRoot string
	binPath     string
	libPath     string
	includePath string
}

func NewVersionWrapperManager(fs afero.Fs, silo *domain.Silo, phpVersion string) *VersionWrapperManager {
	m := &VersionWrapperManager{
		fs:          fs,
		silo:        silo,
		phpVersion:  phpVersion,
		wrapperRoot: utils.VersionWrapperPath(silo, phpVersion),
	}
	m.binPath = filepath.Join(m.wrapperRoot, "bin")
	m.libPath = filepath.Join(m.wrapperRoot, "lib")
	m.includePath = filepath.Join(m.wrapperRoot, "include")
	return m
}

func (m *VersionWrapperManager) Ensure() error {
	dirs := []string{m.binPath, filepath.Join(m.libPath, "pkgconfig"), m.includePath}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("failed to create wrapper dir %s: %w", dir, err)
		}
	}
	return nil
}

func (m *VersionWrapperManager) Cleanup() error {
	if m.fs != nil {
		return m.fs.RemoveAll(m.wrapperRoot)
	}
	return os.RemoveAll(m.wrapperRoot)
}

func (m *VersionWrapperManager) CreatePgConfigWrapper(libPqDepPath string) error {
	wrapperScript := fmt.Sprintf(`#!/bin/sh
# Auto-generated by phpv for PHP %s
WRAPPER_DIR="%s"
WRAPPER_LIB="%s/lib"
WRAPPER_INCLUDE="%s/include"

case "$1" in
  --prefix)
    echo "$WRAPPER_DIR"
    ;;
  --bindir)
    echo "$WRAPPER_DIR/bin"
    ;;
  --includedir)
    echo "$WRAPPER_INCLUDE"
    ;;
  --libdir)
    echo "$WRAPPER_LIB"
    ;;
  --pkgincludedir)
    echo "$WRAPPER_INCLUDE"
    ;;
  --pkglibdir)
    echo "$WRAPPER_LIB"
    ;;
  --version)
    if command -v pg_config >/dev/null 2>&1; then
      pg_config --version 2>/dev/null
    else
      echo "12.0"
    fi
    ;;
  --cflags)
    echo "-I$WRAPPER_INCLUDE"
    ;;
  --libdir)
    echo "$WRAPPER_LIB"
    ;;
  --ldflags)
    echo "-L$WRAPPER_LIB"
    ;;
  --libs)
    echo "-L$WRAPPER_LIB -lpq"
    ;;
  *)
    if command -v /usr/bin/pg_config >/dev/null 2>&1; then
      exec /usr/bin/pg_config "$@"
    elif command -v pg_config >/dev/null 2>&1; then
      exec pg_config "$@"
    else
      echo "pg_config: unknown option: $1" >&2
      exit 1
    fi
    ;;
esac
`, m.phpVersion, m.wrapperRoot, m.wrapperRoot, m.wrapperRoot)

	scriptPath := filepath.Join(m.binPath, "pg_config")
	if err := os.WriteFile(scriptPath, []byte(wrapperScript), 0o755); err != nil {
		return fmt.Errorf("failed to write pg_config wrapper: %w", err)
	}
	return nil
}

func (m *VersionWrapperManager) CreatePkgConfigWrapper() error {
	wrapperScript := fmt.Sprintf(`#!/bin/sh
# Auto-generated by phpv for PHP %s
# This wrapper intercepts pkg-config calls and ensures only phpv-bundled
# packages are found. It completely blocks access to system packages.

WRAPPER_LIB="%s/lib"
WRAPPER_PC_PATH="%s"

# If no arguments, show usage
if [ $# -eq 0 ]; then
  echo "Usage: pkg-config [--version] [--modversion] [--cflags] [--libs] [--libs-only-L] [--libs-only-other] [packages...]"
  exit 0
fi

# Handle --version and --help without package validation
case "$1" in
  --version)
    echo "0.29"
    exit 0
    ;;
  --help)
    echo "Usage: pkg-config [--version] [--modversion] [--cflags] [--libs] [--libs-only-L] [--libs-only-other] [packages...]"
    exit 0
    ;;
esac

# Extract package names from arguments (skip flags)
packages=""
for arg in "$@"; do
  case "$arg" in
    -*) continue ;;
    *) packages="$packages $arg" ;;
  esac
done

# For each requested package, verify it exists in our wrapper path
# If ANY package is not found in our path, fail immediately
# This prevents falling back to system pkg-config
for pkg in $packages; do
  if ! [ -f "$WRAPPER_PC_PATH/${pkg}.pc" ] && ! [ -f "$WRAPPER_PC_PATH/${pkg}-uninstalled.pc" ]; then
    echo "pkg-config: package '$pkg' was not found in $WRAPPER_PC_PATH" >&2
    exit 1
  fi
done

# All packages found in our wrapper - call system pkg-config with ONLY our path
# This guarantees we only get flags for bundled packages, never system ones
export PKG_CONFIG_PATH="$WRAPPER_PC_PATH"

output=$(/usr/bin/pkg-config "$@" 2>&1)
exit_code=$?

# Filter out any system paths that slipped through (defense in depth)
if [ $exit_code -eq 0 ]; then
  result=""
  for token in $output; do
    case "$token" in
      -I/usr/*|-L/usr/*|-L/usr/lib64/*|-L/usr/lib/*) continue ;;
      *) result="${result}${result:+" "}${token}" ;;
    esac
  done
  echo "$result"
else
  echo "$output"
fi

exit $exit_code
`, m.phpVersion, m.wrapperRoot, filepath.Join(m.libPath, "pkgconfig"))

	scriptPath := filepath.Join(m.binPath, "pkg-config")
	if err := os.WriteFile(scriptPath, []byte(wrapperScript), 0o755); err != nil {
		return fmt.Errorf("failed to write pkg-config wrapper: %w", err)
	}
	return nil
}

func (m *VersionWrapperManager) CreateLibSymlink(depName, depVersion, sourceLib string) error {
	if sourceLib == "" {
		return nil
	}
	destLib := filepath.Join(m.libPath, filepath.Base(sourceLib))
	return m.createSymlink(sourceLib, destLib)
}

func (m *VersionWrapperManager) CreateIncludeSymlink(depName, sourceInclude string) error {
	if sourceInclude == "" {
		return nil
	}
	destInclude := filepath.Join(m.includePath, depName)
	return m.createSymlink(sourceInclude, destInclude)
}

func (m *VersionWrapperManager) CreateDepLibSymlink(depName, depVersion string) error {
	depPath := utils.DependencyPath(m.silo, m.phpVersion, depName, depVersion)
	if depPath == "" {
		return nil
	}

	for _, libSubdir := range []string{"lib", "lib64"} {
		sourceDir := filepath.Join(depPath, libSubdir)
		if _, err := os.Stat(sourceDir); err != nil {
			continue
		}

		entries, err := os.ReadDir(sourceDir)
		if err != nil {
			continue
		}

		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			name := entry.Name()
			if !strings.HasSuffix(name, ".so") && !strings.HasSuffix(name, ".a") {
				continue
			}

			sourcePath := filepath.Join(sourceDir, name)
			destPath := filepath.Join(m.libPath, name)

			if _, err := os.Stat(destPath); err == nil {
				continue
			}

			if err := m.createSymlink(sourcePath, destPath); err != nil {
				continue
			}
		}

		pcDir := filepath.Join(sourceDir, "pkgconfig")
		if _, err := os.Stat(pcDir); err == nil {
			destPcDir := filepath.Join(m.libPath, "pkgconfig")
			pcEntries, _ := os.ReadDir(pcDir)
			for _, pcEntry := range pcEntries {
				if pcEntry.IsDir() {
					continue
				}
				sourcePc := filepath.Join(pcDir, pcEntry.Name())
				destPc := filepath.Join(destPcDir, pcEntry.Name())
				if _, err := os.Stat(destPc); err != nil {
					m.createSymlink(sourcePc, destPc)
				}
			}
		}
	}

	return nil
}

func (m *VersionWrapperManager) CreateDepIncludeSymlink(depName, depVersion string) error {
	depPath := utils.DependencyPath(m.silo, m.phpVersion, depName, depVersion)
	if depPath == "" {
		return nil
	}

	for _, incSubdir := range []string{"include", "include64"} {
		sourceDir := filepath.Join(depPath, incSubdir)
		if _, err := os.Stat(sourceDir); err != nil {
			continue
		}

		destDir := filepath.Join(m.includePath, depName)
		if _, err := os.Stat(destDir); err == nil {
			continue
		}

		m.createSymlink(sourceDir, destDir)
		return nil
	}

	return nil
}

func (m *VersionWrapperManager) createSymlink(source, dest string) error {
	var err error
	if m.fs != nil {
		_, err = m.fs.Stat(source)
	} else {
		_, err = os.Stat(source)
	}
	if err != nil {
		return err
	}

	if m.fs != nil {
		existing, _ := m.fs.Stat(dest)
		if existing != nil {
			return nil
		}
	} else {
		if _, err := os.Stat(dest); err == nil {
			return nil
		}
	}

	return os.Symlink(source, dest)
}

func (m *VersionWrapperManager) CreateLibPqWrapper(systemLibPqPath string) error {
	if err := m.CreateLibSymlink("libpq", "", systemLibPqPath); err != nil {
		if systemLibPqPath != "" {
			return fmt.Errorf("failed to create libpq symlink: %w", err)
		}
	}

	wrapperIncludePath := filepath.Join(m.includePath, "libpq")
	if systemLibPqPath != "" {
		systemInclude := filepath.Dir(systemLibPqPath)
		if strings.HasSuffix(systemInclude, "/lib64") {
			systemInclude = strings.TrimSuffix(systemInclude, "/lib64") + "/include"
		} else if strings.HasSuffix(systemInclude, "/lib") {
			systemInclude = strings.TrimSuffix(systemInclude, "/lib") + "/include"
		}
		psqlFeHeader := filepath.Join(systemInclude, "libpq-fe.h")
		if _, err := os.Stat(psqlFeHeader); err == nil {
			m.createSymlink(psqlFeHeader, filepath.Join(wrapperIncludePath, "libpq-fe.h"))
		}

		postgresHeader := filepath.Join(systemInclude, "postgres.h")
		if _, err := os.Stat(postgresHeader); err == nil {
			m.createSymlink(postgresHeader, filepath.Join(wrapperIncludePath, "postgres.h"))
		}
	}

	return nil
}

func (m *VersionWrapperManager) AddSystemLib(libName, systemPath string) error {
	if systemPath == "" {
		return nil
	}

	sourceBase := filepath.Dir(systemPath)
	includeDir := sourceBase
	if strings.HasSuffix(includeDir, "/lib64") {
		includeDir = strings.TrimSuffix(includeDir, "/lib64") + "/include"
	} else if strings.HasSuffix(includeDir, "/lib") {
		includeDir = strings.TrimSuffix(includeDir, "/lib") + "/include"
	}

	libNameLower := strings.ToLower(libName)

	if libNameLower == "libpq" {
		return m.CreateLibPqWrapper(systemPath)
	}

	destLib := filepath.Join(m.libPath, libName+".so")
	m.createSymlink(systemPath, destLib)

	headerDir := filepath.Join(includeDir, libName)
	if _, err := os.Stat(headerDir); err == nil {
		destHeaderDir := filepath.Join(m.includePath, libName)
		m.createSymlink(headerDir, destHeaderDir)
	}

	return nil
}

func (m *VersionWrapperManager) WrapperPath() string {
	return m.wrapperRoot
}

func (m *VersionWrapperManager) BinPath() string {
	return m.binPath
}

func (m *VersionWrapperManager) LibPath() string {
	return m.libPath
}

func (m *VersionWrapperManager) IncludePath() string {
	return m.includePath
}

func (m *VersionWrapperManager) Exists() bool {
	if m.fs != nil {
		exists, _ := afero.DirExists(m.fs, m.wrapperRoot)
		return exists
	}
	_, err := os.Stat(m.wrapperRoot)
	return err == nil
}

func GetSystemLibPqPath() string {
	paths := []string{
		"/usr/lib64/libpq.so",
		"/usr/lib64/libpq.a",
		"/usr/lib/libpq.so",
		"/usr/lib/libpq.a",
		"/usr/local/lib/libpq.so",
		"/usr/local/lib64/libpq.so",
	}
	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}

func GetSystemOpenSSLLibPath() string {
	paths := []string{
		"/usr/lib64/libssl.so",
		"/usr/lib/libssl.so",
		"/usr/lib64/libcrypto.so",
		"/usr/lib/libcrypto.so",
	}
	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}
