package apache

import (
	"encoding/json"
	"os"
	"path/filepath"

	"github.com/supanadit/phpv/domain"
)

// apacheRoot returns the phpv-managed Apache directory (~/.phpv/apache).
func apacheRoot() string {
	return resolvePHPVRoot("apache")
}

// vhostsDir is where phpv-managed vhost configs live.
func vhostsDir() string {
	return filepath.Join(apacheRoot(), "vhosts")
}

// confDir holds phpv-generated include snippets.
func confDir() string {
	return filepath.Join(apacheRoot(), "conf")
}

// logsDir holds per-vhost access/error logs.
func logsDir() string {
	return filepath.Join(apacheRoot(), "logs")
}

// runDir holds PID files.
func runDir() string {
	return filepath.Join(apacheRoot(), "run")
}

// fpmDir holds generated FPM pool configs.
func fpmDir() string {
	return filepath.Join(apacheRoot(), "fpm")
}

// sslDir holds self-signed certs generated by phpv.
func sslDir() string {
	return filepath.Join(apacheRoot(), "ssl")
}

// configPath is the JSON state file describing the configured webserver.
func configPath() string {
	return filepath.Join(apacheRoot(), "apache.json")
}

func resolvePHPVRoot(parts ...string) string {
	root := os.Getenv("PHPV_ROOT")
	if root == "" {
		home, _ := os.UserHomeDir()
		root = filepath.Join(home, ".phpv")
	}
	return filepath.Join(append([]string{root}, parts...)...)
}

// ensureDirs creates all phpv-managed Apache directories.
func ensureDirs() error {
	for _, d := range []string{apacheRoot(), vhostsDir(), confDir(), logsDir(), runDir(), fpmDir(), sslDir()} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return err
		}
	}
	return nil
}

// loadConfig reads apache.json. Returns nil (no error) when the file is absent.
func loadConfig() (*domain.WebserverConfig, error) {
	data, err := os.ReadFile(configPath())
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var cfg domain.WebserverConfig
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}

// saveConfig writes apache.json.
func saveConfig(cfg *domain.WebserverConfig) error {
	if err := ensureDirs(); err != nil {
		return err
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(configPath(), data, 0o644)
}
