package shim

const shimTemplate = `#!/bin/bash
# Auto-generated by phpv. Do not edit.
PHPV_ROOT="${PHPV_ROOT:-$HOME/.phpv}"
{{SYSTEM_BLOCK}}
if [ -n "$PHPV_CURRENT" ]; then
    PHPV_VERSION="$PHPV_CURRENT"
elif [ -f .php-version ] && [ -s .php-version ]; then
    PHPV_VERSION="$(phpv auto-detect-resolve "$(cat .php-version)" 2>/dev/null)"
    if [ -z "$PHPV_VERSION" ]; then
        PHPV_VERSION="$(cat .php-version)"
    fi
elif [ -f .phpvrc ] && [ -s .phpvrc ]; then
    PHPV_VERSION="$(phpv auto-detect-resolve "$(cat .phpvrc)" 2>/dev/null)"
    if [ -z "$PHPV_VERSION" ]; then
        PHPV_VERSION="$(cat .phpvrc)"
    fi
else
    PHPV_VERSION="$(phpv auto-detect-resolve 2>/dev/null || cat "$PHPV_ROOT/default" 2>/dev/null)"
fi
if ! echo "$PHPV_VERSION" | grep -qE '^[0-9]+(\.[0-9]+)*$'; then
    echo "Error: invalid version: $PHPV_VERSION" >&2
    exit 1
fi
if [ -z "$PHPV_VERSION" ]; then
    echo "Error: No PHP version selected. Run 'phpv use <version>' first." >&2
    exit 1
fi
PHPV_PREFIX="$PHPV_ROOT/packages/php/$PHPV_VERSION"
if [ ! -d "$PHPV_PREFIX" ]; then
    echo "Error: PHP version $PHPV_VERSION not found. Run 'phpv install $PHPV_VERSION' first." >&2
    exit 1
fi
export PHPV_CURRENT="$PHPV_VERSION"
# Clean-room: start with only local phpv-managed lib paths.
# The parent's *_LIBRARY_PATH is NOT inherited — use
# PHPV_EXTRA_LD_LIBRARY_PATH to explicitly add system libs.
if [ "$(uname)" = "Darwin" ]; then
    LIB_PATH_VAR="DYLD_LIBRARY_PATH"
else
    LIB_PATH_VAR="LD_LIBRARY_PATH"
fi
eval "$LIB_PATH_VAR=\"\$PHPV_PREFIX/lib\""
for dep_lib in "$PHPV_ROOT/packages"/*/*/lib; do
    [ -d "$dep_lib" ] && eval "$LIB_PATH_VAR=\"\$dep_lib:\$$LIB_PATH_VAR\""
done
if [ -n "$PHPV_EXTRA_LD_LIBRARY_PATH" ]; then
    eval "$LIB_PATH_VAR=\"\$PHPV_EXTRA_LD_LIBRARY_PATH:\$$LIB_PATH_VAR\""
fi
export $LIB_PATH_VAR
{{EXEC}}
`

const systemBinaryBlock = `if [ -f "$PHPV_ROOT/.phpv_system" ]; then
    PHP_PATH="$(command -v {{NAME}} 2>/dev/null)"
    if [ -z "$PHP_PATH" ]; then
        echo "Error: System {{NAME}} not found" >&2
        exit 1
    fi
    exec "$PHP_PATH" "$@"
fi
`

const systemPharBlock = `if [ -f "$PHPV_ROOT/.phpv_system" ]; then
    PHP_PATH="$(command -v php 2>/dev/null)"
    if [ -z "$PHP_PATH" ]; then
        echo "Error: System PHP not found" >&2
        exit 1
    fi
    PHAR_PATH="$HOME/.phpv/packages/php/system/{{PHAR_REL}}"
    if [ ! -f "$PHAR_PATH" ]; then
        echo "Error: {{NAME}} not found for system PHP" >&2
        exit 1
    fi
    exec "$PHP_PATH" "$PHAR_PATH" "$@"
fi
`

const binaryExec = `exec "$PHPV_PREFIX/bin/{{NAME}}" "$@"`
const pharExec = `exec "$PHPV_PREFIX/bin/php" "$PHPV_PREFIX/{{PHAR_REL}}" "$@"`
