package terminal

import "fmt"

func NewNothingHandler() {
	fmt.Println("PHPV - PHP Version Manager")
	fmt.Println()
	fmt.Println("USAGE:")
	fmt.Println("    phpv <command> [arguments]")
	fmt.Println()
	fmt.Println("COMMANDS:")
	fmt.Println("    list                        List available PHP versions (from remote)")
	fmt.Println("    download                    Download PHP source code")
	fmt.Println("    build                       Build and install PHP from source (using Clang)")
	fmt.Println("    install                     Alias for build command")
	fmt.Println("    prune                       Remove all build artifacts")
	fmt.Println()
	fmt.Println("    init [shell]                Output shell initialization script")
	fmt.Println("    use <version>               Set PHP version for current shell session")
	fmt.Println("    shell <version>             Alias for use command")
	fmt.Println("    default [version]           Set/get default PHP version")
	fmt.Println("    versions                    List installed PHP versions")
	fmt.Println("    which                       Show current PHP binary path")
	fmt.Println()
	fmt.Println("    help                        Show this help message")
	fmt.Println()
	fmt.Println("EXAMPLES:")
	fmt.Println("    phpv list                   # List available versions")
	fmt.Println("    phpv list 8                 # List versions for major version 8")
	fmt.Println("    phpv list 8.3               # List versions for major.minor 8.3")
	fmt.Println("    phpv download 8.4           # Download latest PHP 8.4.x source")
	fmt.Println("    phpv build 8.4.14           # Build specific PHP 8.4.14 from source")
	fmt.Println()
	fmt.Println("    phpv init bash              # Setup bash shell integration")
	fmt.Println("    eval \"$(phpv init -)\"        # Add to .bashrc/.zshrc")
	fmt.Println("    phpv use 8.3                # Use PHP 8.3 in current shell")
	fmt.Println("    phpv default 8.3            # Set PHP 8.3 as default")
	fmt.Println("    phpv versions               # List installed versions")
	fmt.Println()
	fmt.Println("SHELL INTEGRATION:")
	fmt.Println("    Add the following to your shell profile:")
	fmt.Println()
	fmt.Println("    # Bash/Zsh:")
	fmt.Println("    eval \"$(phpv init -)\"")
	fmt.Println()
	fmt.Println("    # Fish:")
	fmt.Println("    phpv init fish | source")
	fmt.Println()
	fmt.Println("    # PowerShell:")
	fmt.Println("    Invoke-Expression (phpv init - | Out-String)")
	fmt.Println()
	fmt.Println("ENVIRONMENT VARIABLES:")
	fmt.Println("    PHPV_ROOT    Root directory for phpv (default: ~/.phpv)")
	fmt.Println("    PHP_SOURCE   Source for downloads: 'github' or 'official' (default: github)")
}
