package terminal

import "fmt"

func NewNothingHandler() {
	fmt.Println("PHPV - PHP Version Manager")
	fmt.Println()
	fmt.Println("USAGE:")
	fmt.Println("    phpv [--verbose] <command> [arguments]")
	fmt.Println()
	fmt.Println("OPTIONS:")
	fmt.Println("    --verbose, -v               Show detailed build output (default: show progress bars)")
	fmt.Println()
	fmt.Println("COMMANDS:")
	fmt.Println("    install <version>           Install a specific PHP version (supports partial versions: e.g., 8, 8.3)")
	fmt.Println("    uninstall <version>         Uninstall a specific PHP version (supports partial versions: e.g., 8, 8.3)")
	fmt.Println("    use <version>               Switch to a specific PHP version (supports partial versions: e.g., 8, 8.3)")
	fmt.Println("    current                     Show the current PHP version")
	fmt.Println("    list                        List installed PHP versions")
	fmt.Println("    which                       Show path to current PHP binary")
	fmt.Println()
	fmt.Println("EXAMPLES:")
	fmt.Println("    phpv install 8.3.12         # Install PHP 8.3.12 with progress bars")
	fmt.Println("    phpv --verbose install 8.3  # Install latest 8.3.x with verbose output")
	fmt.Println("    phpv -v install 8           # Install latest 8.x.x with verbose output")
	fmt.Println("    phpv use 8.3.12             # Switch to PHP 8.3.12")
	fmt.Println("    phpv use 8.3                # Switch to latest installed 8.3.x")
	fmt.Println("    phpv use system             # Switch to system PHP")
	fmt.Println("    phpv current                # Show current version")
	fmt.Println("    phpv list                   # List installed versions")
	fmt.Println("    phpv which                  # Show current PHP binary path")
	fmt.Println()
	fmt.Println("ENVIRONMENT VARIABLES:")
	fmt.Println("    PHPV_ROOT    Root directory for phpv (default: ~/.phpv)")
}
